version: 2.0.1.{build}
image: Visual Studio 2017


environment:
  matrix:
  - PlatformToolset: VS15
  - PlatformToolset: VS17

platform:
    - x64
    - x86

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="x86" set archi=x86
    - if "%platform%"=="x86" set platform_input=x86

    - if "%PlatformToolset%"=="VS15" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%
    - if "%PlatformToolset%"=="VS17" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%


build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"\ImgTag\
    - msbuild ImgTag.csproj /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        if ($env:PLATFORM_INPUT -eq "x64") {
            #Push-AppveyorArtifact "ImgTag\bin\$env:PLATFORM\$env:CONFIGURATION\ImgTag.dll" -FileName ImgTag.dll
        }

        if ($env:PLATFORM_INPUT -eq "x86" ) {
            #Push-AppveyorArtifact "ImgTag\bin\$env:CONFIGURATION\ImgTag.dll" -FileName ImgTag.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "VS15") {
            if($env:PLATFORM_INPUT -eq "x64"){
            $ZipFileName = "ImgTag_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
            7z a $ZipFileName "$($env:APPVEYOR_BUILD_FOLDER)\ImgTag\bin\$env:PLATFORM_INPUT\$env:CONFIGURATION\*.dll"
            }
            if($env:PLATFORM_INPUT -eq "x86"){
            $ZipFileName = "ImgTag_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
            7z a $ZipFileName "$($env:APPVEYOR_BUILD_FOLDER)\ImgTag\bin\$env:CONFIGURATION\*.dll"
            }
        }

artifacts:
  - path: ImgTag_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: PhNXrhw03Z0rJZssX/UYyoIofw669wU1GBy/hGq+WJPCXd7mbxDu6Il32Rx0LBH6
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: VS15
        configuration: Release
